// Code generated by cmd/reset; DO NOT EDIT.
package main

// Reset resets programFlags to its zero state.
func (s *programFlags) Reset() {
	if s == nil {
		return
	}
	s.RunAddress = ""
	s.ServerAddress = ""
	s.FileName = ""
	s.Length = 0
	s.Dsn = ""
	s.AuditFile = ""
	s.AuditURL = ""
}
