package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	root, err := os.Getwd()
	if err != nil {
		panic(err)
	}

	pkgs, err := collectPackages(root)
	if err != nil {
		log.Fatal(err)
	}

	for _, pkg := range pkgs {
		structs := findResettableStructs(pkg)

		if len(structs) == 0 {
			continue
		}

		var buf bytes.Buffer
		_, err := fmt.Fprintf(&buf, "// Code generated by cmd/reset; DO NOT EDIT.\n")
		if err != nil {
			return
		}

		_, err = fmt.Fprintf(&buf, "package %s\n\n", pkg.Name)
		if err != nil {
			return
		}

		for _, st := range structs {
			genResetMethod(&buf, st)
		}

		outPath := filepath.Join(pkg.Dir, "reset.gen.go")
		if err := os.WriteFile(outPath, buf.Bytes(), 0644); err != nil {
			panic(err)
		}
	}
}

type packageInfo struct {
	Name string
	Dir  string
	ASTs []*ast.File
}

func collectPackages(root string) ([]*packageInfo, error) {
	var pkgs []*packageInfo
	fset := token.NewFileSet()

	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() && strings.HasSuffix(info.Name(), ".go") && !strings.HasPrefix(info.Name(), "_") {
			if strings.Contains(path, "/vendor/") || strings.Contains(path, "/testdata/") {
				return nil
			}

			f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
			if err != nil {
				return err
			}

			var pkg *packageInfo
			for _, p := range pkgs {
				if filepath.Dir(path) == p.Dir {
					pkg = p
					break
				}
			}
			if pkg == nil {
				pkg = &packageInfo{
					Name: f.Name.Name,
					Dir:  filepath.Dir(path),
				}
				pkgs = append(pkgs, pkg)
			}
			pkg.ASTs = append(pkg.ASTs, f)
		}
		return nil
	})
	return pkgs, err
}

type structInfo struct {
	Name string
	Type *ast.StructType
}

func findResettableStructs(pkg *packageInfo) []*structInfo {
	var res []*structInfo

	for _, f := range pkg.ASTs {
		for _, decl := range f.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			comment := ""
			if genDecl.Doc != nil && len(genDecl.Doc.List) > 0 {
				comment = strings.TrimSpace(genDecl.Doc.Text())
			}

			if !strings.Contains(comment, "generate:reset") {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				res = append(res, &structInfo{
					Name: typeSpec.Name.Name,
					Type: structType,
				})
			}
		}
	}
	return res
}

func genResetMethod(buf *bytes.Buffer, st *structInfo) {
	fmt.Fprintf(buf, "// Reset resets %s to its zero state.\n", st.Name)
	fmt.Fprintf(buf, "func (s *%s) Reset() {\n", st.Name)
	fmt.Fprintln(buf, "\tif s == nil { return }")

	for _, field := range st.Type.Fields.List {
		typStr := exprToString(field.Type)
		for _, nameIdent := range field.Names {
			genResetField(buf, "s."+nameIdent.Name, typStr)
		}
	}

	fmt.Fprintln(buf, "}")
}

func exprToString(expr ast.Expr) string {
	var b strings.Builder
	if err := format.Node(&b, token.NewFileSet(), expr); err != nil {
		return ""
	}
	return b.String()
}

func genResetField(buf *bytes.Buffer, fieldName string, typ string) {
	switch typ {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"uintptr",
		"float32", "float64",
		"complex64", "complex128":
		fmt.Fprintf(buf, "\t%s = 0\n", fieldName)
	case "string":
		fmt.Fprintf(buf, "\t%s = \"\"\n", fieldName)
	case "bool":
		fmt.Fprintf(buf, "\t%s = false\n", fieldName)
	default:
		if strings.HasPrefix(typ, "[") {
			fmt.Fprintf(buf, "\t%s = %s[:0]\n", fieldName, fieldName)
		} else if typ == "[]" || strings.HasPrefix(typ, "[]") { // []T
			fmt.Fprintf(buf, "\t%s = %s[:0]\n", fieldName, fieldName)
		} else if strings.HasPrefix(typ, "*") {
			base := strings.TrimPrefix(typ, "*")
			if isPrimitive(base) {
				fmt.Fprintf(buf, "\tif %s != nil { *%s = 0 }\n", fieldName, fieldName)
			} else {
				fmt.Fprintf(buf, "\tif %s != nil {\n", fieldName)
				fmt.Fprintf(buf, "\t\t%s.Reset()\n", fieldName)
				fmt.Fprintf(buf, "\t}\n")
			}
		} else if strings.HasPrefix(typ, "map[") {
			fmt.Fprintf(buf, "\tclear(%s)\n", fieldName)
		} else {
			fmt.Fprintf(buf, "\tif r, ok := %s.(interface{ Reset() }); ok {\n", fieldName)
			fmt.Fprintf(buf, "\t\tr.Reset()\n")
			fmt.Fprintf(buf, "\t}\n")
		}
	}
}

func isPrimitive(typ string) bool {
	primitives := map[string]bool{
		"int": true, "int8": true, "int16": true, "int32": true, "int64": true,
		"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true,
		"uintptr": true,
		"float32": true, "float64": true,
		"complex64": true, "complex128": true,
		"string": true,
		"bool":   true,
	}
	return primitives[typ]
}
